name: Main

on:
  push:
    branches: [main]

permissions:
  actions: write
  packages: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  linting:
    name: Linting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Hadolint
        uses: hadolint/hadolint-action@v3.3.0

  build:
    name: Build
    needs: linting
    runs-on: ${{ matrix.runs-on.os }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - os: ubuntu-24.04
            platform: linux/amd64
          - os: ubuntu-24.04-arm
            platform: linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Log in to the Container registry
        uses: docker/login-action@v4
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build and Push (ansible)
        uses: specsnl/github-actions/build-image@2.1.0
        with:
          platform: ${{ matrix.runs-on.platform }}
          image-name: ghcr.io/${{ github.repository }}
          dockerfile: Dockerfile
          target: ansible
      - name: Build and Push (k8s)
        uses: specsnl/github-actions/build-image@2.1.0
        with:
          platform: ${{ matrix.runs-on.platform }}
          image-name: ghcr.io/${{ github.repository }}/k8s
          dockerfile: Dockerfile
          target: k8s

  merge:
    name: Merge
    needs: build
    runs-on: ubuntu-24.04
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Create Manifest (ansible)
        uses: specsnl/github-actions/create-manifest@2.1.0
        with:
          image-name: ghcr.io/${{ github.repository }}
          target: ansible
      - name: Create Manifest (k8s)
        uses: specsnl/github-actions/create-manifest@2.1.0
        with:
          image-name: ghcr.io/${{ github.repository }}/k8s
          target: k8s
